var allLocations = [
    {
        name: 'Adirondack Scenic Railroad',
        lat: 43.1041839,
        lng: -75.2254106,
        address: '321 Main Street',
        city: 'Utica',
        state: 'NY',
        zip: '13501',
        phone: '<a href="tel:+18008192291">(800)-819-2291</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/321+Main+St,+Utica,+NY+13501/">Get Directions</a>',
        website: '<a target="_blank" href="http://www.adirondackrr.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },

    {
        name: 'Alberta Prairie Railway',
        lat: 52.321691,
        lng: -112.700174,
        address: '4611 47 Ave',
        city: 'Stettler',
        state: 'AB',
        zip: 'T0C 2L0',
        phone: '<a href="tel:+14037422811">(403)-742-2811</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/4611+47+Ave,+Stettler,+AB+T0C+2L1,+Canada">Get Directions</a>',
        website: '<a target="_blank" href="http://www.absteamtrain.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Aspen Crossing',
        lat: 50.718012,
        lng: -113.351669,
        address: 'Highway 24',
        city: 'Highway 24, Mossleigh',
        state: 'AB',
        zip: 'T0L 1P0',
        phone: '<a href="tel:+14035342129">(403)-534-2129</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Aspen+Crossing,+Highway+24,+Mossleigh,+AB+T0L+1P0,+Canada">Get Directions</a>',
        website: '<a target="_blank" href="http://www.aspencrossing.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'B&O Railroad Museum',
        lat: 39.285425,
        lng: -76.632668,
        address: '901 West Pratt St.',
        city: 'Baltimore',
        state: 'MD',
        zip: '21223',
        phone: '<a href="tel:+14107522490">(410)-752-2490</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/901+W+Pratt+St,+Baltimore,+MD+21223">Get Directions</a>',
        website: '<a target="_blank" href="http://www.borail.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Big South Fork Scenic Railway',
        lat: 36.699023,
        lng: -84.476114,
        address: '100 Henderson St.',
        city: 'Stearns',
        state: 'KY',
        zip: '42647',
        phone: '<a href="tel:+18779447849">(877)-944-7849</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/100+Henderson+St,+Stearns,+KY+42647">Get Directions</a>',
        website: '<a target="_blank" href="http://www.stearnsthepolarexpressride.com /?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Blackstone Valley Tourism Council',
        lat: 41.877307,
        lng: -71.383878,
        address: '175 Main Street # 4',
        city: 'Pawtucket,',
        state: 'RI',
        zip: '02860',
        phone: '<a href="tel:+14014951213">(401)-495-1213</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/175+Main+St+%234,+Pawtucket,+RI+02860">Get Directions</a>',
        website: '<a target="_blank" href="http://www.blackstonevalleypolarexpress.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Branson Scenic Railway',
        lat: 36.643239,
        lng: -93.214983,
        address: '206 East Main Street',
        city: 'Branson',
        state: 'MO',
        zip: '65616',
        phone: '<a href="tel:+18002872462">(800)-287-2462</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/206+E+Main+St,+Branson,+MO+65616">Get Directions</a>',
        website: '<a target="_blank" href="http://www.bransontrain.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'California State Railroad Museum',
        lat: 38.584625,
        lng: -121.504652,
        address: '111 I Street',
        city: 'Sacramento',
        state: 'CA',
        zip: '95814',
        phone: '<a href="tel:+19164458270">(916)-445-8270</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/111+I+St,+Sacramento,+CA+95814">Get Directions</a>',
        website: '<a target="_blank" href="http://www.csrmf.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Catskill Mountain Railroad',
        lat: 41.935319,
        lng: -74.015389,
        address: '149 Aaron Ct.',
        city: 'Kingston',
        state: 'NY',
        zip: '12401',
        phone: '<a href="tel:+18456887400">(845)-688-7400</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/149+Aaron+Ct,+Kingston,+NY+12401">Get Directions</a>',
        website: '<a target="_blank" href="http://www.cmrrevents.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Chehalis-Centralia Railroad Association',
        lat: 46.652330,
        lng: -122.978019,
        address: '1101 Southwest Sylvenus Street',
        city: 'Chehalis',
        state: 'WA',
        zip: '98532',
        phone: '<a href="tel:+13607489593">(360)-748-9593</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/1101+SW+Sylvenus+St,+Chehalis,+WA+98532">Get Directions</a>',
        website: '<a target="_blank" href="http://www.steamtrainride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Chicago Union Station',
        lat: 41.878302,
        lng: -87.640357,
        address: '500 W Jackson Blvd',
        city: 'Chicago',
        state: 'IL',
        zip: '60606',
        phone: '<a href="tel:+13124712501">(312)-471-2501</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/500+W+Jackson+Blvd,+Chicago,+IL+60661">Get Directions</a>',
        website: '<a target="_blank" href="http://www.chicagothepolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Colorado Railroad Museum',
        lat: 39.771368,
        lng: -105.193337,
        address: '17155 W. 44th Avenue',
        city: 'Golden',
        state: 'CO',
        zip: '80403',
        phone: '<a href="tel:+18003656263">(800)-365-6263</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/17155+W+44th+Ave,+Golden,+CO+80403">Get Directions</a>',
        website: '<a target="_blank" href="http://www.coloradorailroadmuseum.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Cuyahoga Valley Scenic Railroad',
        lat: 41.196395,
        lng: -81.577040,
        address: '7600 Canal Road Peninsula',
        city: 'Peninsula',
        state: 'OH',
        zip: '44264',
        phone: '<a href="tel:+18004684070">(800)-468-4070</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Cuyahoga+Valley+Scenic+Railroad,+Ohio">Get Directions</a>',
        website: '<a target="_blank" href="http://www.cvsr.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Delaware River Railroad Excursions',
        lat: 40.688779,
        lng: -75.200871,
        address: '99 Elizabeth St',
        city: 'Phillipsburg',
        state: 'NJ',
        zip: '08865',
        phone: '<a href="tel:+18778724674">(877)-872-4674</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Delaware+River+Railroad+Excursions,+99+Elizabeth+St,+Phillipsburg,+NJ+08865">Get Directions</a>',
        website: '<a target="_blank" href="http://877trainride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Dennison Railroad Depot Museum',
        lat: 40.392508,
        lng: -81.332184,
        address: '400 Center Street',
        city: 'Dennison',
        state: 'OH',
        zip: '44621',
        phone: '<a href="tel:+17409226776">(740)-922-6776</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/400+Center+St,+Dennison,+OH+44621">Get Directions</a>',
        website: '<a target="_blank" href="http://www.dennisondepot.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },


    {
        name: 'Durango & Silverton Narrow Gauge Railroad',
        lat: 37.268179,
        lng: -107.882513,
        address: '479 Main Ave Durango',
        city: 'Durango',
        state: 'CO',
        zip: '81301',
        phone: '<a href="tel:+18778724607">(877)-872-4607</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/479+Main+Ave,+Durango,+CO+81301">Get Directions</a>',
        website: '<a target="_blank" href="http://www.durangotrain.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Durbin & Greenbrier Valley Railroad',
        lat: 38.923169,
        lng: -79.850860,
        address: '6 Railroad Ave',
        city: 'Elkins',
        state: 'WV',
        zip: '26241',
        phone: '<a href="tel:+18776867245">(877)-686-7245</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/6+Railroad+Ave,+Elkins,+WV+26241">Get Directions</a>',
        website: '<a target="_blank" href="http://www.mountainrailwv.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Fox River Trolley Museum',
        lat: 41.989424,
        lng: -88.295861,
        address: '361 South La Fox Street',
        city: 'South Elgin',
        state: 'IL',
        zip: '60177',
        phone: '<a href="tel:+18476974676">(847)-697-4676</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/361+S+La+Fox+St,+South+Elgin,+IL+60177">Get Directions</a>',
        website: '<a target="_blank" href="http://www.foxtrolley.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'French Lick Scenic Railway',
        lat: 38.554863,
        lng: -86.618874,
        address: '1 Monon Drive',
        city: 'French Lick',
        state: 'IN',
        zip: '47432',
        phone: '<a href="tel:+1">800-74-TRAIN</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/1+Monon+Dr,+French+Lick,+IN+47432">Get Directions</a>',
        website: '<a target="_blank" href="http://www.frenchlickscenicrailway.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Gold Coast Railroad Museum',
        lat: 25.626751,
        lng: -80.393098,
        address: '12450 SW 152nd St.',
        city: 'Miami',
        state: 'FL',
        zip: '33177',
        phone: '<a href="tel:+13052530063">(305)-253-0063</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/12450+SW+152nd+St,+Miami,+FL+33177">Get Directions</a>',
        website: '<a target="_blank" href="http://www.gcrm.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Grand Canyon Railway',
        lat: 35.252075,
        lng: -112.191509,
        address: '235 North Grand Canyon Boulevard',
        city: 'Williams',
        state: 'AZ',
        zip: '86046',
        phone: '<a href="tel:+18008438724">(800)-843-8724</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/235+N+Grand+Canyon+Blvd,+Williams,+AZ+86046">Get Directions</a>',
        website: '<a target="_blank" href="http://www.thetrain.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Great Smoky Mountains Railroad',
        lat: 35.430505,
        lng: -83.446957,
        address: '226 Everett Street',
        city: 'Bryson City',
        state: 'NC',
        zip: '28713',
        phone: '<a href="tel:+18008724681">(800)-872-4681</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/226+Everett+St,+Bryson+City,+NC+28713">Get Directions</a>',
        website: '<a target="_blank" href="http://www.gsmr.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Maine Narrow Gauge Railroad',
        lat: 43.662037,
        lng: -70.245777,
        address: '58 Fore Street #6',
        city: 'Portland',
        state: 'ME',
        zip: '04101',
        phone: '<a href="tel:+12078280814">(207)-828-0814</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/58+Fore+St+%236,+Portland,+ME+04101">Get Directions</a>',
        website: '<a target="_blank" href="http://www.mainenarrowgauge.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Medina Railroad Museum',
        lat: 43.218364,
        lng: -78.389739,
        address: '530 West Avenue',
        city: 'Medina',
        state: 'NY',
        zip: '14103',
        phone: '<a href="tel:+15857986106">(585)-798-6106</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/530+West+Ave,+Medina,+NY+14103">Get Directions</a>',
        website: '<a target="_blank" href="http://www.railroadmuseum.net/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Mid-Norfolk Railway',
        lat: 52.678910,
        lng: 0.946994,
        address: 'Station Road',
        city: 'Dereham',
        state: 'Norfolk',
        zip: 'NR19 1DF',
        phone: '<a href="tel:+4401362851723">0(136)-285-1723</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Station+Rd,+Dereham+NR19+1DF,+UK">Get Directions</a>',
        website: '<a target="_blank" href="https://www.midnorfolkthepolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Midland Railway',
        lat: 38.774405,
        lng: -95.200829,
        address: '1515 High Street',
        city: 'Baldwin City',
        state: 'KS',
        zip: '66006',
        phone: '<a href="tel:+19137211211">(913)-721-1211</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/1515+High+St,+Baldwin+City,+KS+66006">Get Directions</a>',
        website: '<a target="_blank" href="https://www.midlandrailway.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Monticello Railway Museum',
        lat: 40.054844,
        lng: -88.559145,
        address: '992 Iron Horse Place',
        city: 'Monticello',
        state: 'IL',
        zip: '61856',
        phone: '<a href="tel:+18777629011">(877)-762-9011</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/992+Iron+Horse+Pl,+Monticello,+IL+61856">Get Directions</a>',
        website: '<a target="_blank" href="http://www.mrym.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Morristown & Erie Railway',
        lat: 40.822758,
        lng: -74.412001,
        address: '1 Railroad Plaza',
        city: 'Whippany',
        state: 'NJ',
        zip: '07981',
        phone: '<a href="tel:+18779876487">(877)-987-6487</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/1+Railroad+Plz,+Whippany,+NJ+07981">Get Directions</a>',
        website: '<a target="_blank" href="http://www.whippanythepolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },

    {
        name: 'Mt. Rainier Railroad & Logging Museum',
        lat: 46.764462,
        lng: -122.193796,
        address: '54124 Mountain Hwy',
        city: 'E Elbe',
        state: 'WA',
        zip: '98330',
        phone: '<a href="tel:+13604926000">(360) 492-6000</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/54124+Mountain+Hwy+E,+Elbe,+WA+98330">Get Directions</a>',
        website: '<a target="_blank" href="https://mtrainierrailroad.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },

    {
        name: 'National Railroad Museum',
        lat: 44.483612,
        lng: -88.048022,
        address: '2285 S. Broadway',
        city: 'Green Bay',
        state: 'WI',
        zip: '54304',
        phone: '<a href="tel:+19204377623">(920)-437-7623</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/2285+S+Broadway,+Green+Bay,+WI+54304">Get Directions</a>',
        website: '<a target="_blank" href="http://www.nationalrrmuseum.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Nevada Northern Railway',
        lat: 39.259694,
        lng: -114.869171,
        address: '11th Street and Avenue A',
        city: 'Ely',
        state: 'NV',
        zip: '89315',
        phone: '<a href="tel:+18664078326">(866)-407-8326</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/E+11th+St+%26+Ave+A,+Ely,+NV+89301">Get Directions</a>',
        website: '<a target="_blank" href="http://www.nnry.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'New Orleans Union Passenger Terminal',
        lat: 29.945853,
        lng: -90.078484,
        address: '1001 Loyola Ave',
        city: 'New Orleans',
        state: 'LA',
        zip: '70113',
        phone: '<a href="tel:+15049304408">(504)-930-4408</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/1001+Loyola+Ave,+New+Orleans,+LA+70113">Get Directions</a>',
        website: '<a target="_blank" href="http://www.nolathepolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'North Carolina Transportation Museum',
        lat: 35.686957,
        lng: -80.434986,
        address: '411 S. Salisbury Ave',
        city: 'Spencer',
        state: 'NC',
        zip: '28159',
        phone: '<a href="tel:+17046362889">(704)-636-2889</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/411+S+Salisbury+Ave,+Spencer,+NC+28159">Get Directions</a>',
        website: '<a target="_blank" href="http://www.nctrans.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'North Fork Trolley Company',
        lat: 40.944793,
        lng: -72.627896,
        address: 'Box 46',
        city: 'Aquebogue',
        state: 'NY',
        zip: '11931',
        phone: '<a href="tel:+16313693031">(631)-369-3031</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Aquebogue,+New+York">Get Directions</a>',
        website: '<a target="_blank" href="http://www.northforktrolley.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Orlando & Northwestern Railway',
        lat: 28.801921,
        lng: -81.725487,
        address: '305 E Ruby Street',
        city: 'Tavares',
        state: 'FL',
        zip: '32778',
        phone: '<a href="tel:+13527427200">(352)-742-7200</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/305+E+Ruby+St,+Tavares,+FL+32778">Get Directions</a>',
        website: '<a target="_blank" href="https://www.orlandothepolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'RAILTOWN 1897 State Historic Park',
        lat: 37.951193,
        lng: -120.417812,
        address: '18115 5th Ave',
        city: 'Jamestown',
        state: 'CA',
        zip: '95327',
        phone: '<a href="tel:+1209984395">(209)-984-395</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/18115+5th+Ave,+Jamestown,+CA+95327">Get Directions</a>',
        website: '<a target="_blank" href="http://www.railtown1897.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Seaton Tramway',
        lat: 50.707672,
        lng: -3.069782,
        address: 'Riverside Depot/Harbour Rd',
        city: 'Devon',
        state: '',
        zip: 'EX12 2NQ',
        phone: '<a href="tel:+440129720375">01297 20375</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Seaton+Tramway">Get Directions</a>',
        website: '<a target="_blank" href="http://www.tram.co.uk//?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'St. Louis Union Station',
        lat: 38.629155,
        lng: -90.208694,
        address: '1820 Market Street St.',
        city: 'Louis',
        state: 'MO',
        zip: '63103',
        phone: '<a href="tel:+13149426942">(314)-942-6942</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/1820+Market+St,+St.+Louis,+MO+63103">Get Directions</a>',
        website: '<a target="_blank" href="http://www.stlpolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Telford Steam Railway',
        lat: 52.653551,
        lng: -2.492662,
        address: 'Horsehay',
        city: 'Shropshire',
        state: '',
        zip: 'TF4 3QG',
        phone: '<a href="tel:+44195250388">44 1952 50388</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/TF4+3QG,+Wellington+Rd,+Horsehay,+Telford,+UK">Get Directions</a>',
        website: '<a target="_blank" href="http://www.midlandsthepolarexpressride.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Texas State Railroad',
        lat: 31.738772,
        lng: -95.569997,
        address: '789 Park Road 70',
        city: 'Palestine',
        state: 'TX',
        zip: '75801',
        phone: '<a href="tel:+18556327729">(855)-632-7729</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/789+Park+Rd+70,+Palestine,+TX+75801">Get Directions</a>',
        website: '<a target="_blank" href="http://www.texasstaterailroad.net/events/polar-express/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Vermont Children\'s Trust Foundation',
        lat: 44.477263,
        lng: -73.214375,
        address: '',
        city: 'Burlington',
        state: 'VT',
        zip: '05401',
        phone: '<a href="tel:+18029518604>(802)-951-8604</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/Vermont+Childrens+Trust+Foundation,+95+St+Paul+St,+Burlington,+VT+05401">Get Directions</a>',
        website: '<a target="_blank" href="http://www.vtchildrenstrust.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Virginia & Truckee Railroad',
        lat: 39.316007,
        lng: -119.646094,
        address: '370 F Street',
        city: 'Carson City',
        state: 'NV',
        zip: '89440',
        phone: '<a href="tel:+17756877410">(775)-687-7410</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/370+F+St,+Virginia+City,+NV+89440">Get Directions</a>',
        website: '<a target="_blank" href="http://www.vtrailway.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Waterloo Central Railway',
        lat: 43.537969,
        lng: -80.556988,
        address: '50 Isabella St St.',
        city: 'Jacobs',
        state: 'ON',
        zip: 'N0B 2N0',
        phone: '<a href="tel:+18888992757">(888)-899-2757</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/50+Isabella+St,+St.+Jacobs,+ON+N0B+2N0,+Canada">Get Directions</a>',
        website: '<a target="_blank" href="http://www.waterloocentralrailway.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'West Coast Railway Heritage Park',
        lat: 49.727580,
        lng: -123.160458,
        address: '39645 Government Rd',
        city: 'Squamish',
        state: 'BC',
        zip: 'V6B 3X2',
        phone: '<a href="tel:+16048989336">(604)-898-9336</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/West+Coast+Railway+Heritage+Park,+39645+Government+Rd,+Squamish,+BC,+Canada">Get Directions</a>',
        website: '<a target="_blank" href="http://www.wcra.org/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'White River Rotary Club',
        lat: 43.648030,
        lng: -72.318954,
        address: '39 South Main Street',
        city: 'White River Junction',
        state: 'VT',
        zip: '05001',
        phone: '<a href="tel:+18022815050">(802)-281-5050</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/39+S+Main+St,+White+River+Junction,+VT+05001">Get Directions</a>',
        website: '<a target="_blank" href="http://www.hartfordvtpolarexpress.com/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },
    {
        name: 'Whitewater Valley Scenic Railroad',
        lat: 39.641463,
        lng: -85.140913,
        address: '455 Market Street',
        city: 'Connersville',
        state: 'IN',
        zip: '47331',
        phone: '<a href="tel:+17658252054">(765)-825-2054</a>',
        directions: '<a target="_blank" href="https://www.google.com/maps/dir/Current+Location/455+Market+St,+Connersville,+IN+47331">Get Directions</a>',
        website: '<a target="_blank" href="/?utm_source=raileventsinc&utm_medium=map">Visit our website</a>',
    },


];